"""Add image column and created date

Revision ID: f6c0e70c8b82
Revises: ed2e59a45f57
Create Date: 2020-06-29 18:09:34.970576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6c0e70c8b82'
down_revision = 'ed2e59a45f57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('image_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image_name')
    op.drop_column('users', 'created')
    # ### end Alembic commands ###
